<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="ScreenshotTranslation.App.Tests" />
    <ProjectReference Include="..\ScreenshotTranslation.Core\ScreenshotTranslation.Core.csproj" />
    <ProjectReference Include="..\ScreenshotTranslation.Infrastructure\ScreenshotTranslation.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <AssemblyName>ScreenshotTranslation</AssemblyName>
    <RootNamespace>ScreenshotTranslation.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AppIcon.ico" />
    <Content Include="Assets\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>AppIcon.ico</TargetPath>
    </Content>
  </ItemGroup>

</Project>
